ColegioTerciario/Controllers/Api/MateriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using ColegioTerciario.Models;
using ColegioTerciario.Models.ViewModels;

namespace ColegioTerciario.Controllers.Api
{
    public class MateriasController : ApiController
    {
        private readonly ColegioTerciarioContext _db;
        public MateriasController()
        {
            _db = new ColegioTerciarioContext();
            ;
        }

        //[HttpGet]
        public IHttpActionResult GetPorCarrera([FromUri]int carreraId)
        {
            var materias = _db.Materias.Where(m => m.MATERIA_CARRERAS_ID == carreraId)
                .Select(m => new {m.ID, m.MATERIA_NOMBRE});
            return Ok(materias);
        }

        [HttpGet]
        public IQueryable<ReactSelectViewModel> SelectMaterias([FromUri]string busqueda)
        {
            return (from m in _db.Materias
                    where (
                        m.MATERIA_NOMBRE.ToLower().Contains(busqueda.ToLower()) ||
                        m.MATERIA_NOMBRE_CORTO.ToLower().Contains(busqueda.ToLower())
                        )

                    select new ReactSelectViewModel
                    {
                        label = m.MATERIA_NOMBRE,
                        value = m.ID.ToString()
                    }).Take(5);
        }
    }
}

ColegioTerciario/Controllers/MateriasController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ColegioTerciario.DAL.Models;
using ColegioTerciario.Models;
using PagedList;

namespace ColegioTerciario.Controllers
{
    public class MateriasController : Controller
    {
        private ColegioTerciarioContext db = new ColegioTerciarioContext();

        // GET: Materias
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            #region Preparando variables para ordenado
            ViewBag.NombreSort = sortOrder == "nombre" ? "nombre_desc" : "nombre";
            ViewBag.NombreCortoSort = sortOrder == "nombre_corto" ? "nombre_corto_desc" : "nombre_corto";
            ViewBag.AnioSort = sortOrder == "anio" ? "anio_desc" : "anio";
            ViewBag.DuracionSort = sortOrder == "duracion" ? "duracion_desc" : "duracion";
            ViewBag.HorasCatedraSort = sortOrder == "horas_catedra" ? "horas_catedra_desc" : "horas_catedra";
            #endregion

            IQueryable<Materia> materias = from m in db.Materias select m;

            #region Busqueda
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                materias = materias.Where(m => m.MATERIA_NOMBRE.ToUpper().Contains(searchString.ToUpper())
                                            || m.MATERIA_NOMBRE.ToUpper().Contains(searchString.ToUpper())
                                       );
            }
            #endregion  

            #region Ordenando en funcion de las variables
            switch (sortOrder)
            {
                case "nombre":
                    materias = materias.OrderBy(m => m.MATERIA_NOMBRE);
                    break;
                case "nombre_desc":
                    materias = materias.OrderByDescending(m => m.MATERIA_NOMBRE);
                    break;
                case "nombre_corto":
                    materias = materias.OrderBy(m => m.MATERIA_NOMBRE_CORTO);
                    break;
                case "nombre_corto_desc":
                    materias = materias.OrderByDescending(m => m.MATERIA_NOMBRE_CORTO);
                    break;
                case "anio":
                    materias = materias.OrderBy(m => m.MATERIA_ANIO);
                    break;
                case "anio_desc":
                    materias = materias.OrderByDescending(m => m.MATERIA_ANIO);
                    break;
                case "duracion":
                    materias = materias.OrderBy(m => m.MATERIA_DURACION);
                    break;
                case "duracion_desc":
                    materias = materias.OrderByDescending(m => m.MATERIA_DURACION);
                    break;
                case "horas_catedra":
                    materias = materias.OrderBy(m => m.MATERIA_HORAS_CATEDRA);
                    break;
                case "horas_catedra_desc":
                    materias = materias.OrderByDescending(m => m.MATERIA_HORAS_CATEDRA);
                    break;
                default:
                    materias = materias.OrderBy(m => m.MATERIA_NOMBRE);
                    break;
            }
            #endregion

            int pageSize = 12;
            int pageNumber = (page ?? 1);
            return View(materias.ToPagedList(pageNumber, pageSize));
        }

        // GET: Materias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Materia materia = db.Materias.Find(id);
            if (materia == null)
            {
                return HttpNotFound();
            }
            return View(materia);
        }

        // GET: Materias/Create
        public ActionResult Create()
        {
            ViewBag.MATERIA_CARRERAS_ID = new SelectList(db.Carreras, "ID", "CARRERA_NOMBRE");
            return View();
        }

        // POST: Materias/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,MATERIA_CODIGO,MATERIA_CARRERAS_ID,MATERIA_ANIO,MATERIA_APROBADAS_PARA_CURSAR,MATERIA_APROBADAS_PARA_RENDIR,MATERIA_CURSADAS_PARA_CURSAR,MATERIA_CURSADAS_PARA_RENDIR,MATERIA_DURACION,MATERIA_HORAS_CATEDRA,MATERIA_NOMBRE,MATERIA_NOMBRE_CORTO")] Materia materia)
        {
            if (ModelState.IsValid)
            {
                db.Materias.Add(materia);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MATERIA_CARRERAS_ID = new SelectList(db.Carreras, "ID", "CARRERA_CODIGO", materia.MATERIA_CARRERAS_ID);
            return View(materia);
        }

        // GET: Materias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Materia materia = db.Materias.Find(id);
            if (materia == null)
            {
                return HttpNotFound();
            }
            ViewBag.MATERIA_CARRERAS_ID = new SelectList(db.Carreras, "ID", "CARRERA_CODIGO", materia.MATERIA_CARRERAS_ID);
            return View(materia);
        }

        // POST: Materias/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,MATERIA_CODIGO,MATERIA_CARRERAS_ID,MATERIA_ANIO,MATERIA_APROBADAS_PARA_CURSAR,MATERIA_APROBADAS_PARA_RENDIR,MATERIA_CURSADAS_PARA_CURSAR,MATERIA_CURSADAS_PARA_RENDIR,MATERIA_DURACION,MATERIA_HORAS_CATEDRA,MATERIA_NOMBRE,MATERIA_NOMBRE_CORTO")] Materia materia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(materia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MATERIA_CARRERAS_ID = new SelectList(db.Carreras, "ID", "CARRERA_CODIGO", materia.MATERIA_CARRERAS_ID);
            return View(materia);
        }

        // GET: Materias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Materia materia = db.Materias.Find(id);
            if (materia == null)
            {
                return HttpNotFound();
            }
            return View(materia);
        }

        // POST: Materias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Materia materia = db.Materias.Find(id);
            db.Materias.Remove(materia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ColegioTerciario/Views/Materias/Create.cshtml
@model ColegioTerciario.DAL.Models.Materia

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Materia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MATERIA_CODIGO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MATERIA_CODIGO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MATERIA_CODIGO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MATERIA_CARRERAS_ID, "MATERIA_CARRERAS_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MATERIA_CARRERAS_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MATERIA_CARRERAS_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MATERIA_ANIO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MATERIA_ANIO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MATERIA_ANIO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MATERIA_APROBADAS_PARA_CURSAR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MATERIA_APROBADAS_PARA_CURSAR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MATERIA_APROBADAS_PARA_CURSAR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MATERIA_APROBADAS_PARA_RENDIR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MATERIA_APROBADAS_PARA_RENDIR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MATERIA_APROBADAS_PARA_RENDIR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MATERIA_CURSADAS_PARA_CURSAR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MATERIA_CURSADAS_PARA_CURSAR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MATERIA_CURSADAS_PARA_CURSAR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MATERIA_CURSADAS_PARA_RENDIR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MATERIA_CURSADAS_PARA_RENDIR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MATERIA_CURSADAS_PARA_RENDIR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MATERIA_DURACION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MATERIA_DURACION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MATERIA_DURACION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MATERIA_HORAS_CATEDRA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MATERIA_HORAS_CATEDRA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MATERIA_HORAS_CATEDRA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MATERIA_NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MATERIA_NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MATERIA_NOMBRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MATERIA_NOMBRE_CORTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MATERIA_NOMBRE_CORTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MATERIA_NOMBRE_CORTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ColegioTerciario/Views/Materias/Delete.cshtml
@model ColegioTerciario.DAL.Models.Materia

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Materia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_CARRERA.CARRERA_CODIGO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_CARRERA.CARRERA_CODIGO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_CODIGO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_CODIGO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_ANIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_ANIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_APROBADAS_PARA_CURSAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_APROBADAS_PARA_CURSAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_APROBADAS_PARA_RENDIR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_APROBADAS_PARA_RENDIR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_CURSADAS_PARA_CURSAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_CURSADAS_PARA_CURSAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_CURSADAS_PARA_RENDIR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_CURSADAS_PARA_RENDIR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_DURACION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_DURACION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_HORAS_CATEDRA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_HORAS_CATEDRA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_NOMBRE_CORTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_NOMBRE_CORTO)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ColegioTerciario/Views/Materias/Details.cshtml
@model ColegioTerciario.DAL.Models.Materia

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Materia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_CARRERA.CARRERA_CODIGO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_CARRERA.CARRERA_CODIGO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_CODIGO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_CODIGO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_ANIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_ANIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_APROBADAS_PARA_CURSAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_APROBADAS_PARA_CURSAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_APROBADAS_PARA_RENDIR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_APROBADAS_PARA_RENDIR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_CURSADAS_PARA_CURSAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_CURSADAS_PARA_CURSAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_CURSADAS_PARA_RENDIR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_CURSADAS_PARA_RENDIR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_DURACION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_DURACION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_HORAS_CATEDRA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_HORAS_CATEDRA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATERIA_NOMBRE_CORTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATERIA_NOMBRE_CORTO)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ColegioTerciario/Views/Materias/Index.cshtml
@model PagedList.IPagedList<ColegioTerciario.DAL.Models.Materia>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Materias", FormMethod.Get))
{
    <p>
        Filtro  @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Filtrar" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("NOMBRE", "Index", new { sortOrder = ViewBag.NombreSort, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("NOMBRE CORTO", "Index", new { sortOrder = ViewBag.NombreCortoSort, currentFilter = ViewBag.CurrentFilter })
        </th>

        <th>
            @Html.ActionLink("AÑO", "Index", new { sortOrder = ViewBag.AnioSort, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("DURACION", "Index", new { sortOrder = ViewBag.DuracionSort, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("HORAS CATEDRA", "Index", new { sortOrder = ViewBag.HorasCatedraSort, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MATERIA_NOMBRE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MATERIA_NOMBRE_CORTO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MATERIA_ANIO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MATERIA_DURACION)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MATERIA_HORAS_CATEDRA)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>
<div>
    Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index",
            new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>